image: node:16-alpine

pipelines:
  default:
#    - step:
#        name: Build and Test
#        script:
#          - npm install
#          - npm test
    - step:
        name: Publish
        deployment: production
        script:
          - npm version from-git -m "Upgrade to %s [skip ci]"
          - git push && git push --tags
          - pipe: atlassian/npm-publish:0.2.0
            variables:
              NPM_TOKEN: $NPM_TOKEN